# Generated by Django 2.1.7 on 2019-03-18 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190306_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='featured_images',
        ),
    ]
